<?php
class bk_section_parent {
    static $bk_ajax_c = array();
    function get_ajax_content() {
        return $bk_ajax_c;
    }
    function cfg_options () {
        $cfg_ops = array (
            'fullwidth' => array (
                'bk_feature1' => array (
                    'title'         => true,
                    'sub_title'     => true,
                    'category_id'   => true,
                    'limit'         => true,
                    'offset'        => true,
                    'order'         => true,
                    'bg_color'      => false,
                    'feature'       => true,
                    'load_more_button' => false,
                ),
                'bk_feature2' => array (
                    'title'         => false,
                    'sub_title'     => false,
                    'category_id'   => true,
                    'limit'         => true,
                    'offset'        => true,
                    'order'         => true,
                    'bg_color'      => true,
                    'feature'       => true,
                ),
                'bk_feature_slider' => array (
                    'title'         => true,
                    'sub_title'     => true,
                    'category_id'   => true,
                    'limit'         => true,
                    'offset'        => true,
                    'order'         => true,
                    'bg_color'      => false,
                    'feature'       => true,
                ),
                'bk_row' => array (
                    'title'         => true,
                    'sub_title'     => true,
                    'category_id'   => true,
                    'limit'         => true,
                    'offset'        => true,
                    'order'         => true,
                    'bg_color'      => false,
                    'feature'       => false,
                ),
                'bk_hero' => array (
                    'title'         => true,
                    'sub_title'     => true,
                    'category_id'   => true,
                    'limit'         => false,
                    'offset'        => true,
                    'order'         => true,
                    'bg_color'      => false,
                    'feature'       => false,
                ),
                'bk_fw_slider' => array (
                    'title'         => true,
                    'sub_title'     => true,
                    'category_id'   => true,
                    'limit'         => true,
                    'offset'        => true,
                    'order'         => true,
                    'bg_color'      => false,
                    'feature'       => true,
                ),
                'bk_square_grid' => array (
                    'title'         => true,
                    'sub_title'     => true,
                    'category_id'   => true,
                    'limit'         => true,
                    'offset'        => true,
                    'order'         => false,
                    'bg_color'      => false,
                    'feature'       => false,
                ),
                'bk_masonry' => array (
                    'title'         => true,
                    'sub_title'     => true,
                    'category_id'   => true,
                    'limit'         => true,
                    'offset'        => true,
                    'order'         => false,
                    'bg_color'      => false,
                    'feature'       => false,
                ),
                'bk_carousel' => array (
                    'title'         => true,
                    'sub_title'     => true,
                    'category_id'   => true,
                    'limit'         => true,
                    'offset'        => true,
                    'order'         => true,
                    'bg_color'      => true,
                    'feature'       => false,
                ),
                'bk_carousel_type2' => array (
                    'title'         => true,
                    'sub_title'     => false,
                    'category_id'   => true,
                    'limit'         => true,
                    'offset'        => true,
                    'order'         => true,
                    'bg_color'      => true,
                    'feature'       => false,
                ),
            ),
            'has_sb' => array (
                'bk_block_1' => array (
                    'title'         => true,
                    'sub_title'     => true,
                    'category_id'   => true,
                    'limit'         => false,
                    'offset'        => true,
                    'order'         => true,
                    'bg_color'      => false,
                    'feature'       => false,
                ),
                'bk_block_2' => array (
                    'title'         => true,
                    'sub_title'     => true,
                    'category_id'   => true,
                    'limit'         => true,
                    'offset'        => true,
                    'order'         => true,
                    'bg_color'      => false,
                    'feature'       => false,
                ),
                'bk_classic_blog' => array (
                    'title'         => true,
                    'sub_title'     => true,
                    'category_id'   => true,
                    'limit'         => true,
                    'offset'        => true,
                    'order'         => false,
                    'bg_color'      => false,
                    'feature'       => false,
                ),
                'bk_large_blog' => array (
                    'title'         => true,
                    'sub_title'     => true,
                    'category_id'   => true,
                    'limit'         => true,
                    'offset'        => true,
                    'order'         => false,
                    'bg_color'      => false,
                    'feature'       => false,
                ),
            ),
        );
        return $cfg_ops;
    }
    
}